ADDRESS: 1 Address
AMT_BOUGHT: 0
CITY: Los Alamitos
CREDIT_CARD: '1111222233334444'
CVV: '111'
EMAIL: email@email.com
EXP_DATE_MONTH: '01'
EXP_DATE_YEAR: '2000'
FIRST_NAME: Firsty
LAST_NAME: Lasty
MAX_TO_BUY: 1
PHONE: '##########'
STATE: CA
TARGET_PRICE_3060: 500
TARGET_PRICE_3070: 800
TARGET_PRICE_3080: 900
ZIPCODE: '12345'
