FIRST_NAME: 'Firsty'
LAST_NAME: 'Lasty'
EMAIL: 'email@email.com'
PHONE: '##########'
ADDRESS: '1 Address'
ZIPCODE: '12345'
CITY: 'Los Alamitos'
STATE: 'CA'
CREDIT_CARD: '1111222233334444'
EXP_DATE_MONTH: '01'
EXP_DATE_YEAR: '2000'
CVV: '111'